/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:e4438a43-bbf2-4381-9a4d-f898b5993777",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_dJtcBD4Xk",
    "aws_user_pools_web_client_id": "184s83eqsbf0n3unhhvbq7togk",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "studentViewEnrollments",
            "endpoint": "https://3iws0uqwdl.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        },
        {
            "name": "studentViewCourses",
            "endpoint": "https://n1murh6cx9.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        },
        {
            "name": "openStudentAccount",
            "endpoint": "https://4o8m1mc4cg.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        },
        {
            "name": "loginStudentAccount",
            "endpoint": "https://nd3g6rh4vj.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        },
        {
            "name": "studentRecommendCourses",
            "endpoint": "https://89p1ojcq9g.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        },
        {
            "name": "studentUpdateProgress",
            "endpoint": "https://papixkmme8.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        },
        {
            "name": "studentViewProgress",
            "endpoint": "https://nbnctbqpp0.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        },
        {
            "name": "studentEnrollStudent",
            "endpoint": "https://jbyx6majpc.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        },
        {
            "name": "openAdvisorAccount",
            "endpoint": "https://vkhli4kvhl.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        },
        {
            "name": "loginAdvisorAccount",
            "endpoint": "https://klcdj8ggzd.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        },
        {
            "name": "advisorViewStudentProgress",
            "endpoint": "https://o659yeay17.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        },
        {
            "name": "advisorRecommendCourses",
            "endpoint": "https://kkjl5sd7vi.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        },
        {
            "name": "advisorViewStudent",
            "endpoint": "https://77et8rpf6i.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        },
        {
            "name": "studentRequestAdvisorHelp",
            "endpoint": "https://el96dlmu39.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        },
        {
            "name": "advisorRespondToStudentRequest",
            "endpoint": "https://hunmkjno1h.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
